### PR TITLE
Initial draft of design document

### PR DESCRIPTION
**Pull request by jeromekelleher**
Any thoughts @benjeffery, @Billyzhang1229?

### CODE REVIEW

**Review by Billyzhang1229 — APPROVED** [review]
LGTM

**Comment by benjeffery** [comment]
Some thoughts:

- `numba` could be an optional dependency? We could try to import and print a warning if it isn't installed? Down side is this might be missed if the default is to not have it installed, on the plus side we allow phylokit to be used as pure-python.

- A `phylokit.Tree` would be good so that we don't inadvertently use attributes form `tskit`. This would define what attributes are the minimal set for phylokit and phylokit methods would be methods on the tree. The `Tree` constructor could take either arrays or man object that had the arrays as attributes.

**Comment by jeromekelleher** [comment]
> numba could be an optional dependency? We could try to import and print a warning if it isn't installed? Down side is this might be missed if the default is to not have it installed, on the plus side we allow phylokit to be used as pure-python.

You could, but I don't really see the advantage and it would add quite a bit of complexity. Let's just back platforms that support numba. (Are you thinking of the browser here?)

> A phylokit.Tree would be good so that we don't inadvertently use attributes form tskit. This would define what attributes are the minimal set for phylokit and phylokit methods would be methods on the tree. The Tree constructor could take either arrays or man object that had the arrays as attributes.

I'm thinking of a more "dataset" oriented approach like we have in sgkit, where rather than an object with particular attibutes/methods is expected, we expect particular arrays to exist. I think this will be valuable when we start thinking about how to do things involving data (say, doing parsimony). The first argument dataset will define the tree (via the expected arrays) and will also contain some data, and we can then automatically parallelise using Dask etc. 

All a bit wooly right now, but I definitely want to avoid having a traditional "object oriented" interface here. For now, we can just develop with the tskit Trees and see how things look as we add more types of functionality.

**Comment by benjeffery** [comment]
> > numba could be an optional dependency? We could try to import and print a warning if it isn't installed? Down side is this might be missed if the default is to not have it installed, on the plus side we allow phylokit to be used as pure-python.
> 
> You could, but I don't really see the advantage and it would add quite a bit of complexity. Let's just back platforms that support numba. (Are you thinking of the browser here?)

Yes, I expect `numba` to make it into `pyodide` eventually, the issue is https://github.com/pyodide/pyodide/issues/621, no progress so far. To my mind, the only complexity is defining a custom decorator that tries to get numba, but falls back to returning the undecorated function.

**Comment by jeromekelleher** [comment]
Yeah, that's true. We could also use this as a way to have project-wide defaults for the numba jitting (like cache=True).

**Pull request merged**
