### PR TITLE
Added initial dataset and UPGMA inference

### PR DESCRIPTION
**Pull request by jeromekelleher**
Had some good fun with this - the idea is to start defining the initial interface so that we can nicely connect up with data. It's essentially a mash-up between the interfaces of tskit and sgkit.

Here's some output showing what we get when we run the upgma tree building algorithm. The idea is that we can combine the tree and variant data into the one dataset, so that it's nice and combined and consistent.

The trees are the input and output trees from the upgma tree inference, just to show that the inference algorithm gives something that roughly looks right.

Any thoughts @benjeffery @Billyzhang1229?

```
<xarray.Dataset>                                                                 
Dimensions:             (nodes: 16, samples: 8, variants: 22, alleles: 4,                                             
                         ploidy: 1)                                                                                   
Dimensions without coordinates: nodes, samples, variants, alleles, ploidy                                             
Data variables:                                                                                                       
    node_parent         (nodes) int32 9 12 8 10 8 10 9 ... 11 12 13 14 14 -1 -1                                       
    node_time           (nodes) float64 0.0 0.0 0.0 0.0 0.0 ... 5.0 6.0 7.0 inf                                       
    node_left_child     (nodes) int32 -1 -1 -1 -1 -1 -1 -1 -1 2 0 3 7 1 8 12 14                                       
    node_right_sib      (nodes) int32 6 10 4 5 -1 -1 -1 ... -1 -1 -1 13 -1 -1 -1                                      
    sample_node         (samples) int32 0 1 2 3 4 5 6 7                                                               
    variant_contig      (variants) int64 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0                                      
    variant_position    (variants) int64 5 6 7 8 10 12 13 ... 31 32 34 36 37 39                                       
    variant_allele      (variants, alleles) |S1 b'C' b'A' b'' ... b'A' b'' b''                                        
    sample_id           (samples) <U5 'tsk_0' 'tsk_1' ... 'tsk_6' 'tsk_7'                                             
    call_genotype       (variants, samples, ploidy) int32 0 1 0 1 0 ... 1 0 1 1                                       
    call_genotype_mask  (variants, samples, ploidy) bool False False ... False                                         
3.09┊        14       ┊                                                                                               
    ┊     ┏━━━┻━━━┓   ┊                                    
1.01┊    13       ┃   ┊                                                                                               
    ┊  ┏━━┻━┓     ┃   ┊                                                                                               
0.44┊ 12    ┃     ┃   ┊                                                                                               
    ┊ ┏┻┓   ┃     ┃   ┊                                                                                               
0.39┊ ┃ ┃  11     ┃   ┊                                                                                               
    ┊ ┃ ┃  ┏┻━┓   ┃   ┊                                                                                               
0.19┊ ┃ ┃  ┃  ┃  10   ┊                                                                                               
    ┊ ┃ ┃  ┃  ┃ ┏━┻┓  ┊                                                                                               
0.09┊ ┃ ┃  ┃  ┃ ┃  9  ┊                                                                                               
    ┊ ┃ ┃  ┃  ┃ ┃ ┏┻┓ ┊                                                                                               
0.01┊ ┃ ┃  8  ┃ ┃ ┃ ┃ ┊                                                                                               
    ┊ ┃ ┃ ┏┻┓ ┃ ┃ ┃ ┃ ┊                                                                                               
0.00┊ 0 6 2 4 7 1 3 5 ┊                                                                                               
    0                40                                                                                               
                                                                                                                      
7.00┊        14       ┊                                                                                               
    ┊     ┏━━━┻━━━┓   ┊                                                                                               
6.00┊    13       ┃   ┊                                                                                               
    ┊   ┏━┻━━┓    ┃   ┊                                                                                               
5.00┊   ┃    ┃   12   ┊                                                                                               
    ┊   ┃    ┃  ┏━┻┓  ┊                                                                                               
4.00┊  11    ┃  ┃  ┃  ┊                                                                                               
    ┊  ┏┻━┓  ┃  ┃  ┃  ┊                                                                                               
3.00┊  ┃  ┃  ┃  ┃ 10  ┊                                                                                               
    ┊  ┃  ┃  ┃  ┃ ┏┻┓ ┊                                                                                               
2.00┊  9  ┃  ┃  ┃ ┃ ┃ ┊                                                                                               
    ┊ ┏┻┓ ┃  ┃  ┃ ┃ ┃ ┊                                                                                               
1.00┊ ┃ ┃ ┃  8  ┃ ┃ ┃ ┊                                    
    ┊ ┃ ┃ ┃ ┏┻┓ ┃ ┃ ┃ ┊                                    
0.00┊ 0 6 7 2 4 1 3 5 ┊                                    
    0                 1                                    
```

### CODE REVIEW

**Review by benjeffery — APPROVED** [review]
Nice.
So the input to the various methods will always be an xarray with each method having specific requirements for the arrays that it contains? And then we have methods to create that xarray from, say, plain arrays, tskit or a newick file?

**Comment by jeromekelleher** [comment]
Looks like coverage is failing because of something similar to https://github.com/numba/numba/issues/8002 

Probably simplest to do our own jit-disabling I think.

**Comment by benjeffery** [comment]
> Looks like coverage is failing because of something similar to [numba/numba#8002](https://github.com/numba/numba/issues/8002)
> 
> Probably simplest to do our own jit-disabling I think.



> Looks like coverage is failing because of something similar to [numba/numba#8002](https://github.com/numba/numba/issues/8002)
> 
> Probably simplest to do our own jit-disabling I think.

Looks like a good fix.

**Comment by jeromekelleher** [comment]
I'm going to merge this now as there's a reasonable framework in place. I ended up adding basic newick import export so that we could interoperate with other libraries a bit, and hopefully make testing of various operations a bit easier.

**Pull request merged**
